import type { Metadata } from "next";
import { Oswald, Libre_Franklin } from "next/font/google";
import "./globals.css";

import HeaderMain from "@/components/layout/header/HeaderMain";
import FooterMain from "@/Components/layout/footer/FooterMain";

const oswaldSans = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});

const librefranklin = Libre_Franklin({
  variable: "--font-libre-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswaldSans.variable} ${librefranklin.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <div className="lg:flex lg:h-screen">
          <HeaderMain />
          <main id="main" className="bg-background/10">
            {children}
          </main>
        </div>
        <FooterMain />
      </body>
    </html>
  );
}
