import type { Metadata } from "next";
import { Oswald, Libre_Franklin } from "next/font/google";
import "./globals.css";

const oswaldSans = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});

const librefranklin = Libre_Franklin({
  variable: "--font-libre-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswaldSans.variable} ${librefranklin.variable} h-full antialiased`}
      suppressHydrationWarning
      cz-shortcut-listen="true"
      
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
